language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py -q install

# command to run tests
script: 
  - py.test --doctest-modules

